version: "3.2"

services:
  pgstore:
    image: postgres:12.4
    container_name: pgstore
    restart: unless-stopped
    environment:
      POSTGRES_USER: adminroot
      POSTGRES_PASSWORD: storepassword
      POSTGRES_DB: pg_store
      TZ: "UTC"
      PGTZ: "UTC"
    ports:
      - 5432:5432
    networks:
      - default

  # front-end:
  #   container_name: store_online_fe
  #   image: front-end
  #   restart: unless-stopped
  #   # restart: always
  #   env_file:
  #     - ./frontend/.env.staging
  #   build: ./frontend
  #   working_dir: /app
  #   ports:
  #     - 9000:5173
    # networks:
      # - default
